### ISSUE TITLE
kindling-agent-xxx CrashLoopBackOff

### ISSUE THREAD

**Issue by song90625** [KindlingProject/kindling#508]
**Describe the bug**
i install kindling agent and the pod status is  CrashLoopBackOff

the kubectl describe tool displays the following error：

![image](https://user-images.githubusercontent.com/7663292/236158105-1c60efbc-defa-4be5-af71-ea4db112023c.png)

**Comment by hwz779866221** [comment]
You can refer to [FAQ](http://kindling.harmonycloud.cn/docs/installation/faq/)
Due to Kindling's lack of CO-RE support for eBPF code, the agent needs to use compiled artifacts corresponding to the kernel version at startup whether using a kernel module or eBPF. We have adapted some common kernel versions in advance, maybe your kernel version is not on the list. The steps provided in the FAQ involve compiling the kernel module and eBPF, which will be automatically selected by the agent based on the kernel version when it starts. The logic for this part can be found in the file collector/docker/kindling-probe-loader.

**Comment by hwz779866221** [comment]
You can refer to [FAQ](http://kindling.harmonycloud.cn/docs/installation/faq/)
Due to Kindling's lack of CO-RE support for eBPF code, the agent needs to use compiled artifacts corresponding to the **kernel version** at startup whether using a kernel module or eBPF. We have adapted some common kernel versions in advance, maybe your kernel version is not on the list. The steps provided in the FAQ involve **compiling the kernel module and eBPF**, which will be automatically selected by the agent based on the kernel version when it starts. The logic for this part can be found in the file _collector/docker/kindling-probe-loader_.
